meta_product_name: "TechCompass"
meta_title: "TechCompass - Take control of your tech career"
meta_description: "Our platform will take you from aspiring professional, to actual professional.
Let our app make your job search as easy and productive as possible."
meta_image: "Cover_image.png" # should exist in `app/assets/images/`
